
function analyzeText() {
    const text = document.getElementById('userText').value;

    if (text.trim() === '') {
        alert('Please enter some text to analyze!');
        return;
    }

    if (text.length < 50) {
        alert('Please enter at least 50 characters for accurate analysis!');
        return;
    }

    // Show loading
    document.getElementById('result').style.display = 'block';
    document.getElementById('resultContent').innerHTML = `
        <div class="loading">
            <p>🔍 Analyzing content...</p>
            <p style="color:#aaa; font-size:0.9rem">Detecting AI source...</p>
        </div>
    `;

    fetch('analyze.php', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'text=' + encodeURIComponent(text)
    })
    .then(response => response.json())
    .then(data => {
        if (data.error) {
            alert(data.error);
            return;
        }

        const isAI = data.result === 'AI Generated';
        const emoji = isAI ? '🤖' : '👤';
        const color = isAI ? '#ff4444' : '#00cc66';

        // AI Source emoji
        let sourceEmoji = '';
        let sourceName = data.ai_source;

        if (data.ai_source === 'ChatGPT') {
            sourceEmoji = '🟢';
        } else if (data.ai_source === 'Gemini') {
            sourceEmoji = '🔵';
        } else if (data.ai_source === 'Claude') {
            sourceEmoji = '🟠';
        } else if (data.ai_source === 'Human') {
            sourceEmoji = '👤';
        } else {
            sourceEmoji = '❓';
        }

        // Source scores
        const sourceScores = data.source_scores || {};

        document.getElementById('resultContent').innerHTML = `
            <div class="result-card" style="border-color: ${color}">
                
                <!-- Main Result -->
                <h2 style="color: ${color}">${emoji} ${data.result}</h2>

                <!-- AI Source -->
                ${isAI ? `
                <div class="source-box">
                    <p>Likely Generated By:</p>
                    <h3>${sourceEmoji} ${sourceName}</h3>
                </div>
                ` : ''}

                <!-- AI vs Human Score -->
                <div class="scores">
                    <div class="score-item">
                        <span class="score-label">🤖 AI Score</span>
                        <div class="progress-bar">
                            <div class="progress" 
                                style="width:${data.ai_score}%; 
                                background:#ff4444">
                            </div>
                        </div>
                        <span class="score-value">${data.ai_score}%</span>
                    </div>
                    
                    <div class="score-item">
                        <span class="score-label">👤 Human Score</span>
                        <div class="progress-bar">
                            <div class="progress" 
                                style="width:${data.human_score}%; 
                                background:#00cc66">
                            </div>
                        </div>
                        <span class="score-value">${data.human_score}%</span>
                    </div>
                </div>

                <!-- Source Breakdown -->
                ${isAI ? `
                <div class="source-breakdown">
                    <p style="color:#aaa; margin-bottom:10px">
                        Source Analysis:
                    </p>
                    <div class="score-item">
                        <span class="score-label">🟢 ChatGPT</span>
                        <div class="progress-bar">
                            <div class="progress" 
                                style="width:${Math.min(sourceScores.chatgpt || 0, 100)}%; 
                                background:#74aa9c">
                            </div>
                        </div>
                        <span class="score-value">
                            ${sourceScores.chatgpt || 0}%
                        </span>
                    </div>
                    <div class="score-item">
                        <span class="score-label">🔵 Gemini</span>
                        <div class="progress-bar">
                            <div class="progress" 
                                style="width:${Math.min(sourceScores.gemini || 0, 100)}%; 
                                background:#4285f4">
                            </div>
                        </div>
                        <span class="score-value">
                            ${sourceScores.gemini || 0}%
                        </span>
                    </div>
                    <div class="score-item">
                        <span class="score-label">🟠 Claude</span>
                        <div class="progress-bar">
                            <div class="progress" 
                                style="width:${Math.min(sourceScores.claude || 0, 100)}%; 
                                background:#ff6b35">
                            </div>
                        </div>
                        <span class="score-value">
                            ${sourceScores.claude || 0}%
                        </span>
                    </div>
                </div>
                ` : ''}

                <!-- Stats -->
                <div class="stats">
                    <p>📝 Word Count: <strong>${data.word_count}</strong></p>
                </div>

            </div>
        `;
    })
    .catch(error => {
        document.getElementById('resultContent').innerHTML = `
            <p style="color:red">Error analyzing text. Please try again.</p>
        `;
    });
}
<?php
session_start();
require 'config.php';
header("Cache-Control: no-store, no-cache, must-revalidate");
header("Pragma: no-cache");

if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

$username = $_SESSION['username'];
$user_id = $_SESSION['user_id'];

$total = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM analyses WHERE user_id='$user_id'"))['c'];
$ai_count = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) as c FROM analyses WHERE user_id='$user_id' AND result LIKE '%AI%'"))['c'];
$human_count = $total - $ai_count;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - InkGuard</title>
    <link rel="stylesheet" href="style.css">
    <style>
        * { margin:0; padding:0; box-sizing:border-box; }
        body {
            font-family: 'Segoe UI', sans-serif;
            background: #050510;
            color: #fff;
            min-height: 100vh;
            overflow-x: hidden;
        }
        body::before {
            content: '';
            position: fixed;
            top:-50%; left:-50%;
            width:200%; height:200%;
            background:
                radial-gradient(ellipse at 20% 50%,rgba(124,124,255,0.15) 0%,transparent 50%),
                radial-gradient(ellipse at 80% 20%,rgba(0,204,102,0.1) 0%,transparent 50%),
                radial-gradient(ellipse at 50% 80%,rgba(255,68,68,0.08) 0%,transparent 50%);
            z-index:0;
            animation:bgMove 15s ease infinite alternate;
        }
        @keyframes bgMove {
            0%{transform:translate(0,0)}
            100%{transform:translate(30px,20px)}
        }
        .navbar {
            position:sticky; top:0; z-index:100;
            display:flex; align-items:center;
            justify-content:space-between;
            padding:0 30px; height:65px;
            background:rgba(10,10,26,0.85);
            backdrop-filter:blur(20px);
            border-bottom:1px solid rgba(124,124,255,0.2);
        }
        .navbar-brand {
            display:flex; align-items:center;
            gap:10px; text-decoration:none;
        }
        .brand-icon {
            width:38px; height:38px;
            background:linear-gradient(135deg,#7c7cff,#5555dd);
            border-radius:10px;
            display:flex; align-items:center;
            justify-content:center; font-size:20px;
            box-shadow:0 0 15px rgba(124,124,255,0.4);
        }
        .brand-name {
            font-size:20px; font-weight:800;
            background:linear-gradient(135deg,#7c7cff,#00cc66);
            -webkit-background-clip:text;
            -webkit-text-fill-color:transparent;
        }
        .navbar-right {
            display:flex; align-items:center; gap:8px;
        }
        .user-badge {
            display:flex; align-items:center; gap:8px;
            background:rgba(124,124,255,0.1);
            border:1px solid rgba(124,124,255,0.3);
            padding:6px 14px; border-radius:20px;
            font-size:13px; color:#ccc;
        }
        .user-avatar {
            width:28px; height:28px;
            background:linear-gradient(135deg,#7c7cff,#5555dd);
            border-radius:50%;
            display:flex; align-items:center;
            justify-content:center;
            font-size:13px; font-weight:700;
        }
        .nav-link {
            padding:7px 16px; border-radius:8px;
            font-size:13px; color:#aaa;
            text-decoration:none; transition:all 0.2s;
            border:1px solid transparent;
        }
        .nav-link:hover {
            background:rgba(124,124,255,0.1);
            color:#fff; border-color:rgba(124,124,255,0.3);
        }
        .nav-link.danger { color:#ff6b6b; }
        .nav-link.danger:hover {
            background:rgba(255,68,68,0.1);
            border-color:rgba(255,68,68,0.3);
        }
        .page {
            position:relative; z-index:1;
            max-width:1000px; margin:0 auto;
            padding:30px 20px;
        }
        .welcome-section { margin-bottom:30px; }
        .welcome-section h2 {
            font-size:28px; font-weight:800; margin-bottom:6px;
        }
        .welcome-section h2 span {
            background:linear-gradient(135deg,#7c7cff,#00cc66);
            -webkit-background-clip:text;
            -webkit-text-fill-color:transparent;
        }
        .welcome-section p { color:#888; font-size:14px; }
        .stats-row {
            display:grid;
            grid-template-columns:repeat(3,1fr);
            gap:16px; margin-bottom:24px;
        }
        .stat-card {
            background:rgba(255,255,255,0.03);
            border:1px solid rgba(255,255,255,0.08);
            border-radius:14px; padding:20px;
            backdrop-filter:blur(10px); transition:all 0.3s;
        }
        .stat-card:hover {
            border-color:rgba(124,124,255,0.3);
            transform:translateY(-2px);
        }
        .stat-card .num {
            font-size:32px; font-weight:900;
            line-height:1; margin-bottom:4px;
        }
        .stat-card .label { font-size:12px; color:#888; }
        .glass-card {
            background:rgba(255,255,255,0.03);
            border:1px solid rgba(255,255,255,0.08);
            border-radius:20px; padding:28px;
            backdrop-filter:blur(10px);
            margin-bottom:24px; transition:border-color 0.3s;
        }
        .glass-card:focus-within {
            border-color:rgba(124,124,255,0.4);
        }
        .glass-card h2 {
            font-size:18px; font-weight:700;
            margin-bottom:6px; color:#fff;
        }
        .glass-card p {
            font-size:13px; color:#888; margin-bottom:18px;
        }

        /* Tabs */
        .tab-buttons {
            display:flex; gap:10px; margin-bottom:24px;
        }
        .tab-btn {
            flex:1; padding:12px; border:none;
            border-radius:10px; font-size:14px;
            font-weight:700; cursor:pointer;
            transition:all 0.3s;
        }
        .tab-btn.active {
            background:linear-gradient(135deg,#7c7cff,#5555dd);
            color:#fff;
            box-shadow:0 4px 15px rgba(124,124,255,0.3);
        }
        .tab-btn.inactive {
            background:rgba(255,255,255,0.05);
            color:#aaa;
            border:1px solid rgba(255,255,255,0.1);
        }
        .tab-btn.inactive:hover {
            background:rgba(124,124,255,0.1);
            color:#fff;
        }

        .text-input {
            width:100%; min-height:180px;
            background:rgba(0,0,0,0.3);
            border:1px solid rgba(255,255,255,0.1);
            border-radius:12px; padding:16px;
            color:#fff; font-size:14px;
            font-family:inherit; resize:vertical;
            line-height:1.7; transition:border-color 0.3s;
        }
        .text-input:focus {
            outline:none;
            border-color:rgba(124,124,255,0.5);
        }
        .text-input::placeholder { color:#555; }
        .input-footer {
            display:flex; justify-content:space-between;
            align-items:center; margin-top:12px;
        }
        .char-count { font-size:12px; color:#555; }
        .btn-analyze {
            padding:13px 30px;
            background:linear-gradient(135deg,#7c7cff,#5555dd);
            color:#fff; border:none; border-radius:12px;
            font-size:15px; font-weight:700; cursor:pointer;
            transition:all 0.3s;
            box-shadow:0 4px 20px rgba(124,124,255,0.3);
            display:flex; align-items:center; gap:8px;
        }
        .btn-analyze:hover {
            transform:translateY(-2px);
            box-shadow:0 8px 25px rgba(124,124,255,0.5);
        }
        .btn-humanize {
            padding:13px 30px;
            background:linear-gradient(135deg,#00cc66,#009944);
            color:#fff; border:none; border-radius:12px;
            font-size:15px; font-weight:700; cursor:pointer;
            transition:all 0.3s;
            box-shadow:0 4px 20px rgba(0,204,102,0.3);
            display:flex; align-items:center; gap:8px;
        }
        .btn-humanize:hover {
            transform:translateY(-2px);
            box-shadow:0 8px 25px rgba(0,204,102,0.5);
        }
        .btn-clear {
            padding:13px 20px;
            background:rgba(255,255,255,0.05);
            color:#888; border:1px solid rgba(255,255,255,0.1);
            border-radius:12px; font-size:14px;
            cursor:pointer; transition:all 0.2s;
        }
        .btn-clear:hover {
            background:rgba(255,68,68,0.1);
            color:#ff6b6b; border-color:rgba(255,68,68,0.3);
        }
        .loading-wrap { text-align:center; padding:30px; }
        .spinner {
            width:40px; height:40px;
            border:3px solid rgba(124,124,255,0.2);
            border-top-color:#7c7cff;
            border-radius:50%;
            animation:spin 0.8s linear infinite;
            margin:0 auto 14px;
        }
        @keyframes spin { to{transform:rotate(360deg)} }
        .scores-grid {
            display:grid; grid-template-columns:1fr 1fr;
            gap:16px; margin-bottom:20px;
        }
        .score-item label {
            display:flex; justify-content:space-between;
            font-size:13px; color:#aaa; margin-bottom:6px;
        }
        .score-bar {
            height:10px; background:rgba(0,0,0,0.4);
            border-radius:99px; overflow:hidden;
        }
        .score-fill {
            height:100%; border-radius:99px;
            transition:width 1s cubic-bezier(0.4,0,0.2,1);
        }
        .score-num {
            font-size:24px; font-weight:900; margin-top:4px;
        }
        .source-section {
            border-top:1px solid rgba(255,255,255,0.08);
            padding-top:18px; margin-top:4px;
        }
        .source-title { font-size:13px; color:#888; margin-bottom:12px; }
        .source-row {
            display:flex; align-items:center;
            gap:10px; margin-bottom:10px;
        }
        .source-name {
            min-width:85px; font-size:13px; color:#ccc;
            display:flex; align-items:center; gap:6px;
        }
        .source-bar-wrap {
            flex:1; height:7px;
            background:rgba(0,0,0,0.4);
            border-radius:99px; overflow:hidden;
        }
        .source-bar-fill { height:100%; border-radius:99px; transition:width 1s ease; }
        .source-pct {
            font-size:13px; font-weight:700;
            min-width:38px; text-align:right;
        }
        .tools-section h2 {
            font-size:18px; font-weight:700;
            margin-bottom:16px; color:#ccc;
        }
        .tools-grid {
            display:grid;
            grid-template-columns:repeat(3,1fr);
            gap:14px;
        }
        .tool-card {
            background:rgba(255,255,255,0.03);
            border:1px solid rgba(255,255,255,0.08);
            border-radius:16px; padding:22px 18px;
            text-decoration:none; color:#fff;
            transition:all 0.3s; display:block;
        }
        .tool-card:hover {
            background:rgba(124,124,255,0.08);
            border-color:rgba(124,124,255,0.35);
            transform:translateY(-3px);
            box-shadow:0 8px 25px rgba(124,124,255,0.15);
        }
        .tool-emoji {
            font-size:28px; margin-bottom:10px; display:block;
        }
        .tool-name { font-size:14px; font-weight:700; margin-bottom:4px; }
        .tool-desc { font-size:11px; color:#666; }
        @media(max-width:600px){
            .stats-row{grid-template-columns:1fr}
            .tools-grid{grid-template-columns:repeat(2,1fr)}
            .scores-grid{grid-template-columns:1fr}
            .navbar{padding:0 15px}
            .tab-buttons{flex-direction:column}
        }
    </style>
</head>
<body>

<!-- Navbar -->
<nav class="navbar">
    <a href="dashboard.php" class="navbar-brand">
        <div class="brand-icon">🛡️</div>
        <span class="brand-name">InkGuard</span>
    </a>
    <div class="navbar-right">
        <div class="user-badge">
            <div class="user-avatar">
                <?= strtoupper(substr($username, 0, 1)) ?>
            </div>
            <?= htmlspecialchars($username) ?>
        </div>
        <a href="history.php" class="nav-link">📋 History</a>
        <a href="audit_log.php" class="nav-link">📊 Audit</a>
        <a href="logout.php" class="nav-link danger">🚪 Logout</a>
    </div>
</nav>

<div class="page">

    <!-- Welcome -->
    <div class="welcome-section">
        <h2>Welcome back, <span><?= htmlspecialchars($username) ?></span> 👋</h2>
        <p>Protect your content with AI-powered detection and analysis tools</p>
    </div>

    <!-- Stats -->
    <div class="stats-row">
        <div class="stat-card">
            <div class="num" style="color:#7c7cff"><?= $total ?></div>
            <div class="label">📊 Total Analyses</div>
        </div>
        <div class="stat-card">
            <div class="num" style="color:#ff4444"><?= $ai_count ?></div>
            <div class="label">🤖 AI Detected</div>
        </div>
        <div class="stat-card">
            <div class="num" style="color:#00cc66"><?= $human_count ?></div>
            <div class="label">👤 Human Written</div>
        </div>
    </div>

    <!-- Tab Buttons -->
    <div class="tab-buttons">
        <button class="tab-btn active" id="tab-detector"
            onclick="showTab('detector')">
            🔍 Content Detector
        </button>
        <button class="tab-btn inactive" id="tab-humanizer"
            onclick="showTab('humanizer')">
            ✍️ AI to Human
        </button>
    </div>

    <!-- Content Detector Tab -->
    <div id="tab-detector-content">
        <div class="glass-card">
            <h2>🔍 Content Detector</h2>
            <p>Paste any text to detect if it was written by AI or a Human</p>
            <textarea class="text-input" id="userText"
                placeholder="Paste your text here to analyze..."
                oninput="updateCount()">
            </textarea>
            <div class="input-footer">
                <span class="char-count">
                    <span id="charCount">0</span> / 5000 characters
                </span>
                <div style="display:flex; gap:10px;">
                    <button class="btn-clear" onclick="clearText()">
                        🗑️ Clear
                    </button>
                    <button class="btn-analyze" onclick="analyzeText()">
                        🔍 Analyze Content
                    </button>
                </div>
            </div>
        </div>
        <div class="glass-card" id="result" style="display:none;">
            <h2>📊 Analysis Result</h2>
            <div id="resultContent"></div>
        </div>
    </div>

    <!-- AI to Human Tab -->
    <div id="tab-humanizer-content" style="display:none;">
        <div class="glass-card">
            <h2>✍️ AI to Human Writing</h2>
            <p>Paste AI-generated text to convert it to natural human writing</p>
            <textarea class="text-input" id="aiText"
                placeholder="Paste AI-generated text here to humanize..."
                oninput="updateAiCount()">
            </textarea>
            <div class="input-footer">
                <span class="char-count">
                    <span id="aiCharCount">0</span> / 5000 characters
                </span>
                <div style="display:flex; gap:10px;">
                    <button class="btn-clear" onclick="clearAiText()">
                        🗑️ Clear
                    </button>
                    <button class="btn-humanize" onclick="humanizeText()">
                        ✍️ Convert to Human
                    </button>
                </div>
            </div>
        </div>
        <div class="glass-card" id="humanResult" style="display:none;">
            <h2>✍️ Humanized Result</h2>
            <div id="humanContent"></div>
        </div>
    </div>

    <!-- Tools -->
    <div class="tools-section">
        <h2>🛠️ Safety Tools</h2>
        <div class="tools-grid">
            <a href="detector.php" class="tool-card">
                <span class="tool-emoji">🔍</span>
                <div class="tool-name">Content Detector</div>
                <div class="tool-desc">Detect AI vs Human writing</div>
            </a>
            <a href="plagiarism.php" class="tool-card">
                <span class="tool-emoji">📄</span>
                <div class="tool-name">Plagiarism Checker</div>
                <div class="tool-desc">Check content originality</div>
            </a>
            <a href="brand_rules.php" class="tool-card">
                <span class="tool-emoji">📋</span>
                <div class="tool-name">Brand Rules</div>
                <div class="tool-desc">Protect your brand voice</div>
            </a>
            <a href="prompt_scanner.php" class="tool-card">
                <span class="tool-emoji">🛡️</span>
                <div class="tool-name">Prompt Scanner</div>
                <div class="tool-desc">Detect injection attacks</div>
            </a>
            <a href="audit_log.php" class="tool-card">
                <span class="tool-emoji">📊</span>
                <div class="tool-name">Audit Log</div>
                <div class="tool-desc">Full analysis history</div>
            </a>
            <a href="risk_score.php" class="tool-card">
                <span class="tool-emoji">⚠️</span>
                <div class="tool-name">Risk Score</div>
                <div class="tool-desc">Overall risk assessment</div>
            </a>
        </div>
    </div>

</div>

<script src="script.js"></script>
<script>
// Tab switching
function showTab(tab) {
    document.getElementById('tab-detector-content').style.display = 'none';
    document.getElementById('tab-humanizer-content').style.display = 'none';
    document.getElementById('tab-detector').className = 'tab-btn inactive';
    document.getElementById('tab-humanizer').className = 'tab-btn inactive';
    document.getElementById('tab-' + tab + '-content').style.display = 'block';
    document.getElementById('tab-' + tab).className = 'tab-btn active';
}

// Detector
function updateCount() {
    document.getElementById('charCount').textContent =
        document.getElementById('userText').value.length;
}

function clearText() {
    document.getElementById('userText').value = '';
    document.getElementById('charCount').textContent = '0';
    document.getElementById('result').style.display = 'none';
}

function analyzeText() {
    const text = document.getElementById('userText').value;
    if (!text.trim()) { alert('Please enter some text!'); return; }
    if (text.length < 50) { alert('Please enter at least 50 characters!'); return; }

    const resultBox = document.getElementById('result');
    const resultContent = document.getElementById('resultContent');
    resultBox.style.display = 'block';
    resultContent.innerHTML = `
        <div class="loading-wrap">
            <div class="spinner"></div>
            <p style="color:#7c7cff; font-weight:600">🔍 Analyzing content...</p>
        </div>`;
    resultBox.scrollIntoView({behavior:'smooth', block:'start'});

    fetch('analyze.php', {
        method:'POST',
        headers:{'Content-Type':'application/x-www-form-urlencoded'},
        body:'text=' + encodeURIComponent(text)
    })
    .then(r => r.json())
    .then(data => {
        if (data.error) { alert(data.error); return; }
        const isAI = data.result === 'AI Generated';
        const isMixed = data.result === 'Mixed Content';
        const color = isAI ? '#ff4444' : isMixed ? '#ffd700' : '#00cc66';
        const emoji = isAI ? '🤖' : isMixed ? '⚠️' : '👤';
        const bgColor = isAI ? 'rgba(255,68,68,0.08)' :
            isMixed ? 'rgba(255,215,0,0.08)' : 'rgba(0,204,102,0.08)';
        let sourceEmoji = '❓';
        if (data.ai_source === 'ChatGPT') sourceEmoji = '🟢';
        else if (data.ai_source === 'Gemini') sourceEmoji = '🔵';
        else if (data.ai_source === 'Claude') sourceEmoji = '🟠';
        else if (data.ai_source === 'Human') sourceEmoji = '👤';
        const s = data.source_scores || {};

        resultContent.innerHTML = `
            <div style="border-radius:16px; padding:24px;
                border:2px solid ${color}; background:${bgColor}">
                <div style="display:flex; align-items:center;
                    gap:12px; margin-bottom:20px">
                    <div style="width:50px; height:50px;
                        border-radius:14px; background:${color}22;
                        display:flex; align-items:center;
                        justify-content:center; font-size:24px">
                        ${emoji}
                    </div>
                    <div>
                        <div style="font-size:22px; font-weight:800;
                            color:${color}">${data.result}</div>
                        <div style="font-size:13px; color:#aaa; margin-top:2px">
                            ${isAI || isMixed ?
                                sourceEmoji + ' Likely: ' + data.ai_source :
                                '✅ No AI patterns detected'}
                        </div>
                    </div>
                </div>
                <div class="scores-grid">
                    <div class="score-item">
                        <label>
                            <span>🤖 AI Score</span>
                            <span style="color:#ff4444; font-weight:700">
                                ${data.ai_score}%
                            </span>
                        </label>
                        <div class="score-bar">
                            <div class="score-fill"
                                style="width:${data.ai_score}%;
                                background:linear-gradient(90deg,#ff4444,#ff6b6b)">
                            </div>
                        </div>
                        <div class="score-num" style="color:#ff4444">
                            ${data.ai_score}%
                        </div>
                    </div>
                    <div class="score-item">
                        <label>
                            <span>👤 Human Score</span>
                            <span style="color:#00cc66; font-weight:700">
                                ${data.human_score}%
                            </span>
                        </label>
                        <div class="score-bar">
                            <div class="score-fill"
                                style="width:${data.human_score}%;
                                background:linear-gradient(90deg,#00cc66,#00ff88)">
                            </div>
                        </div>
                        <div class="score-num" style="color:#00cc66">
                            ${data.human_score}%
                        </div>
                    </div>
                </div>
                ${isAI || isMixed ? `
                <div class="source-section">
                    <div class="source-title">🔎 Source Analysis:</div>
                    <div class="source-row">
                        <div class="source-name">🟢 ChatGPT</div>
                        <div class="source-bar-wrap">
                            <div class="source-bar-fill"
                                style="width:${Math.min(s.chatgpt||0,100)}%;
                                background:#74aa9c"></div>
                        </div>
                        <div class="source-pct" style="color:#74aa9c">
                            ${s.chatgpt||0}%
                        </div>
                    </div>
                    <div class="source-row">
                        <div class="source-name">🔵 Gemini</div>
                        <div class="source-bar-wrap">
                            <div class="source-bar-fill"
                                style="width:${Math.min(s.gemini||0,100)}%;
                                background:#4285f4"></div>
                        </div>
                        <div class="source-pct" style="color:#4285f4">
                            ${s.gemini||0}%
                        </div>
                    </div>
                    <div class="source-row">
                        <div class="source-name">🟠 Claude</div>
                        <div class="source-bar-wrap">
                            <div class="source-bar-fill"
                                style="width:${Math.min(s.claude||0,100)}%;
                                background:#ff6b35"></div>
                        </div>
                        <div class="source-pct" style="color:#ff6b35">
                            ${s.claude||0}%
                        </div>
                    </div>
                </div>` : ''}
                <div style="display:flex; gap:20px; padding-top:16px;
                    border-top:1px solid rgba(255,255,255,0.08); margin-top:16px">
                    <span style="color:#555; font-size:13px">
                        📝 Words: <strong style="color:#ccc">${data.word_count}</strong>
                    </span>
                    <span style="color:#555; font-size:13px">
                        📊 Confidence:
                        <strong style="color:${color}">${data.ai_score}%</strong>
                    </span>
                </div>
            </div>`;
    })
    .catch(() => {
        resultContent.innerHTML = `
            <p style="color:#ff4444; text-align:center">
                ❌ Error analyzing. Please try again.
            </p>`;
    });
}
function humanizeText() {
    const text = document.getElementById('aiText').value;
    if (!text.trim()) {
        alert('Please enter some text!');
        return;
    }
    if (text.length < 50) {
        alert('Please enter at least 50 characters!');
        return;
    }

    const resultBox = document.getElementById('humanResult');
    const resultContent = document.getElementById('humanContent');
    resultBox.style.display = 'block';
    resultContent.innerHTML = `
        <div class="loading-wrap">
            <div class="spinner"
                style="border-top-color:#00cc66"></div>
            <p style="color:#00cc66; font-weight:600">
                ✍️ Converting to academic human writing...
            </p>
        </div>`;

    fetch('humanize.php', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: 'text=' + encodeURIComponent(text) +
              '&style=academic'
    })
    .then(r => r.json())
    .then(data => {
        if (data.error) { alert(data.error); return; }

        const scoreColor = data.humanize_score > 30 ?
            '#00cc66' : '#ffd700';

        resultContent.innerHTML = `
            <div style="border:2px solid #00cc66;
                border-radius:14px; padding:24px;
                background:rgba(0,204,102,0.05)">

                <!-- Header -->
                <div style="display:flex;
                    justify-content:space-between;
                    align-items:center; margin-bottom:16px">
                    <h3 style="color:#00cc66; font-size:16px">
                        ✅ Academic Humanization Complete!
                    </h3>
                    <button onclick="copyHumanized()"
                        style="background:#7c7cff; color:#fff;
                        border:none; padding:8px 16px;
                        border-radius:8px; cursor:pointer;
                        font-size:13px; font-weight:600">
                        📋 Copy Text
                    </button>
                </div>

                <!-- Stats -->
                <div style="display:grid;
                    grid-template-columns:repeat(3,1fr);
                    gap:12px; margin-bottom:16px">
                    <div style="background:rgba(0,0,0,0.3);
                        border-radius:10px; padding:12px;
                        text-align:center">
                        <div style="font-size:22px;
                            font-weight:900;
                            color:${scoreColor}">
                            ${data.humanize_score}%
                        </div>
                        <div style="font-size:11px; color:#888;
                            margin-top:2px">
                            Changed
                        </div>
                    </div>
                    <div style="background:rgba(0,0,0,0.3);
                        border-radius:10px; padding:12px;
                        text-align:center">
                        <div style="font-size:22px;
                            font-weight:900; color:#7c7cff">
                            ${data.original_words}
                        </div>
                        <div style="font-size:11px; color:#888;
                            margin-top:2px">
                            Original Words
                        </div>
                    </div>
                    <div style="background:rgba(0,0,0,0.3);
                        border-radius:10px; padding:12px;
                        text-align:center">
                        <div style="font-size:22px;
                            font-weight:900; color:#00cc66">
                            ${data.humanized_words}
                        </div>
                        <div style="font-size:11px; color:#888;
                            margin-top:2px">
                            Output Words
                        </div>
                    </div>
                </div>

                <!-- Progress bar -->
                <div style="margin-bottom:20px">
                    <div style="display:flex;
                        justify-content:space-between;
                        font-size:12px; color:#888;
                        margin-bottom:6px">
                        <span>Humanization Level</span>
                        <span style="color:${scoreColor};
                            font-weight:700">
                            ${data.humanize_score}%
                        </span>
                    </div>
                    <div style="height:8px; background:#333;
                        border-radius:99px; overflow:hidden">
                        <div style="width:${data.humanize_score}%;
                            height:100%; background:${scoreColor};
                            border-radius:99px;
                            transition:width 1s ease">
                        </div>
                    </div>
                </div>

                <!-- Side by side comparison -->
                <div style="display:grid;
                    grid-template-columns:1fr 1fr;
                    gap:12px; margin-bottom:16px">
                    <div>
                        <div style="font-size:12px; color:#888;
                            margin-bottom:6px; font-weight:600">
                            🤖 Original (AI)
                        </div>
                        <div style="background:rgba(255,68,68,0.05);
                            border:1px solid rgba(255,68,68,0.2);
                            border-radius:8px; padding:12px;
                            font-size:12px; color:#aaa;
                            line-height:1.7; max-height:150px;
                            overflow-y:auto">
                            ${data.original}
                        </div>
                    </div>
                    <div>
                        <div style="font-size:12px; color:#00cc66;
                            margin-bottom:6px; font-weight:600">
                            👤 Humanized (Academic)
                        </div>
                        <div style="background:rgba(0,204,102,0.05);
                            border:1px solid rgba(0,204,102,0.2);
                            border-radius:8px; padding:12px;
                            font-size:12px; color:#ccc;
                            line-height:1.7; max-height:150px;
                            overflow-y:auto">
                            ${data.humanized}
                        </div>
                    </div>
                </div>

                <!-- Full output -->
                <div style="font-size:12px; color:#888;
                    margin-bottom:8px; font-weight:600">
                    📄 Full Humanized Text:
                </div>
                <div style="background:rgba(0,0,0,0.3);
                    border:1px solid rgba(0,204,102,0.3);
                    border-radius:10px; padding:16px;
                    max-height:300px; overflow-y:auto">
                    <p id="humanizedOutput"
                        style="color:#ccc; line-height:1.9;
                        font-size:13px; white-space:pre-wrap">
                        ${data.humanized}
                    </p>
                </div>

                <!-- Academic tips -->
                <div style="margin-top:16px; padding:12px;
                    background:rgba(124,124,255,0.05);
                    border:1px solid rgba(124,124,255,0.2);
                    border-radius:8px">
                    <div style="font-size:12px; color:#7c7cff;
                        font-weight:700; margin-bottom:6px">
                        💡 Academic Writing Tips:
                    </div>
                    <ul style="font-size:11px; color:#888;
                        padding-left:16px; line-height:1.8">
                        <li>Review and personalize the output with your own voice</li>
                        <li>Add specific examples and evidence from your research</li>
                        <li>Ensure citations are properly formatted</li>
                        <li>Read aloud to check for natural flow</li>
                    </ul>
                </div>

            </div>`;
    })
    .catch(() => {
        resultContent.innerHTML = `
            <p style="color:#ff4444; text-align:center">
                ❌ Error. Please try again.
            </p>`;
    });
}

function copyHumanized() {
    const text = document.getElementById('humanizedOutput')
        ?.innerText;
    if (text) {
        navigator.clipboard.writeText(text).then(() => {
            alert('✅ Copied to clipboard!');
        });
    }
}
